-- Table: example
CREATE TABLE `example` (
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);