CREATE TABLE `z_user_permission` (
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `user` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE `z_user`
  ADD COLUMN `active` TINYINT(1) NOT NULL DEFAULT 1 AFTER `languageId`,
  ADD COLUMN `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `active`,
  MODIFY COLUMN `email` VARCHAR(255) NULL,
  ADD UNIQUE KEY `uq_user_email` (`email`);