CREATE TABLE IF NOT EXISTS `z_organization` (
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci;

ALTER TABLE `z_user`
  ADD COLUMN IF NOT EXISTS `organizationId` INT NULL DEFAULT NULL AFTER `id`,
  ADD INDEX IF NOT EXISTS `organizationId` (`organizationId`);
