ALTER TABLE `z_logintoken`
    ADD COLUMN IF NOT EXISTS `device` VARCHAR(255) NULL DEFAULT NULL AFTER `name`,
    ADD COLUMN IF NOT EXISTS `reason` VARCHAR(255) NULL DEFAULT NULL AFTER `device`,
    ADD COLUMN IF NOT EXISTS `ip_creation` VARCHAR(45) NULL DEFAULT NULL AFTER `reason`,
    ADD COLUMN IF NOT EXISTS `ip_last` VARCHAR(45) NULL DEFAULT NULL AFTER `ip_creation`;
