ALTER TABLE `z_logintoken`
    ADD COLUMN IF NOT EXISTS `name` VARCHAR(255) NULL DEFAULT NULL AFTER `userId_exec`,
    ADD COLUMN IF NOT EXISTS `is_permanent` TINYINT(1) NOT NULL DEFAULT 0 AFTER `name`,
    ADD COLUMN IF NOT EXISTS `is_apikey` TINYINT(1) NOT NULL DEFAULT 0 AFTER `is_permanent`;
