CREATE TABLE IF NOT EXISTS `z_organization` (
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE `z_user`
  ADD COLUMN IF NOT EXISTS `organizationId` INT NULL DEFAULT NULL AFTER `id`;