CREATE TABLE IF NOT EXISTS `z_2fa_challenge` (
  `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `userId` INT NOT NULL,
  `device` VARCHAR(255) NULL DEFAULT NULL,
  `ip_creation` VARCHAR(45) NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  INDEX `token` (`token`)
);

ALTER TABLE `z_logintoken`
  ADD COLUMN IF NOT EXISTS `last_2fa` TIMESTAMP NULL DEFAULT NULL AFTER `last_used`;

ALTER TABLE `z_user`
  ADD COLUMN IF NOT EXISTS `totp_secret` VARCHAR(255) NULL DEFAULT NULL AFTER `salt`,
  ADD COLUMN IF NOT EXISTS `totp_confirmed_at` TIMESTAMP NULL DEFAULT NULL AFTER `totp_secret`;
