ALTER TABLE `z_file`
    ADD COLUMN IF NOT EXISTS `uuid` VARCHAR(36) NOT NULL DEFAULT UUID_v7() AFTER `id`,
    ADD UNIQUE INDEX IF NOT EXISTS `uuid` (`uuid`);

ALTER TABLE `z_user`
    ADD COLUMN IF NOT EXISTS `uuid` VARCHAR(36) NOT NULL DEFAULT UUID_v7() AFTER `id`,
    ADD UNIQUE INDEX IF NOT EXISTS `uuid` (`uuid`);

ALTER TABLE `z_organization`
    ADD COLUMN IF NOT EXISTS `uuid` VARCHAR(36) NOT NULL DEFAULT UUID_v7() AFTER `id`,
    ADD UNIQUE INDEX IF NOT EXISTS `uuid` (`uuid`);

ALTER TABLE `z_role`
    ADD COLUMN IF NOT EXISTS `uuid` VARCHAR(36) NOT NULL DEFAULT UUID_v7() AFTER `id`,
    ADD UNIQUE INDEX IF NOT EXISTS `uuid` (`uuid`);

ALTER TABLE `z_logintoken`
    ADD COLUMN IF NOT EXISTS `uuid` VARCHAR(36) NOT NULL DEFAULT UUID_v7() AFTER `id`,
    ADD UNIQUE INDEX IF NOT EXISTS `uuid` (`uuid`);
