<?php

    /**
     * Renders deterministic kitchen-sink pages used as the source-of-truth
     * for our visual-regression specs (tests/cypress/e2e/visual/...).
     *
     * Each action renders one audit page — the spec screenshots it and diffs
     * against a committed baseline so we catch FA / Bootstrap upgrade drift.
     */
    class VisualController extends z_controller {

        public function action_icons(Request $req, Response $res) {
            return $res->render(
                "visual/icons",
                ["icons" => $this->icons()],
                "layout/min_layout.php",
            );
        }

        public function action_bootstrap(Request $req, Response $res) {
            return $res->render(
                "visual/bootstrap",
                [],
                "layout/min_layout.php",
            );
        }

        private function icons(): array {
            // Aggregate of every Font Awesome class observed across our
            // customer codebases (selbststaendigkeit-de, torch-dashboard,
            // fubble, bautalents, customer-portal) plus the framework's own
            // admin layout. Each entry is [prefix, name]. Order is fixed so
            // the rendered grid is byte-stable across runs.
            return [
                // FA4-style names (use bare "fa", resolved through v4-shims)
                ["fa", "address-book"],
                ["fa", "address-card"],
                ["fa", "android"],
                ["fa", "angle-double-right"],
                ["fa", "angle-down"],
                ["fa", "angle-right"],
                ["fa", "archive"],
                ["fa", "arrow-circle-o-right"],
                ["fa", "arrow-down"],
                ["fa", "arrow-left"],
                ["fa", "arrow-right"],
                ["fa", "arrow-up"],
                ["fa", "ban"],
                ["fa", "bar-chart"],
                ["fa", "bars"],
                ["fa", "bell"],
                ["fa", "book"],
                ["fa", "bookmark-o"],
                ["fa", "briefcase"],
                ["fa", "brush"],
                ["fa", "building"],
                ["fa", "building-o"],
                ["fa", "bullhorn"],
                ["fa", "bullseye"],
                ["fa", "calculator"],
                ["fa", "calendar"],
                ["fa", "calendar-check-o"],
                ["fa", "caret-down"],
                ["fa", "caret-right"],
                ["fa", "caret-square-o-right"],
                ["fa", "cash-register"],
                ["fa", "chalkboard-teacher"],
                ["fa", "check"],
                ["fa", "check-circle"],
                ["fa", "check-circle-o"],
                ["fa", "chevron-right"],
                ["fa", "circle"],
                ["fa", "clipboard"],
                ["fa", "clipboard-list"],
                ["fa", "clock"],
                ["fa", "clock-o"],
                ["fa", "close"],
                ["fa", "cloud-download"],
                ["fa", "cloud-upload"],
                ["fa", "cog"],
                ["fa", "cogs"],
                ["fa", "columns"],
                ["fa", "comment"],
                ["fa", "comment-o"],
                ["fa", "commenting"],
                ["fa", "comments"],
                ["fa", "comments-o"],
                ["fa", "connectdevelop"],
                ["fa", "cookie-bite"],
                ["fa", "copy"],
                ["fa", "cubes"],
                ["fa", "dashboard"],
                ["fa", "database"],
                ["fa", "download"],
                ["fa", "ellipsis-v"],
                ["fa", "envelope"],
                ["fa", "envelope-o"],
                ["fa", "exclamation-circle"],
                ["fa", "exclamation-triangle"],
                ["fa", "external-link"],
                ["fa", "external-link-square-alt"],
                ["fa", "eye"],
                ["fa", "file"],
                ["fa", "file-alt"],
                ["fa", "file-csv"],
                ["fa", "file-image-o"],
                ["fa", "file-invoice"],
                ["fa", "file-pdf"],
                ["fa", "file-pdf-o"],
                ["fa", "file-text-o"],
                ["fa", "files-o"],
                ["fa", "filter"],
                ["fa", "fire"],
                ["fa", "flag"],
                ["fa", "forward"],
                ["fa", "globe"],
                ["fa", "graduation-cap"],
                ["fa", "handshake-o"],
                ["fa", "heart-o"],
                ["fa", "history"],
                ["fa", "id-card-alt"],
                ["fa", "image"],
                ["fa", "info"],
                ["fa", "info-circle"],
                ["fa", "key"],
                ["fa", "level-down"],
                ["fa", "level-up"],
                ["fa", "line-chart"],
                ["fa", "link"],
                ["fa", "list"],
                ["fa", "list-ul"],
                ["fa", "lock"],
                ["fa", "lock-open"],
                ["fa", "mail-bulk"],
                ["fa", "map-marker"],
                ["fa", "map-marker-alt"],
                ["fa", "map-signs"],
                ["fa", "microphone-slash"],
                ["fa", "minus"],
                ["fa", "minus-circle"],
                ["fa", "money"],
                ["fa", "money-check"],
                ["fa", "object-group"],
                ["fa", "palette"],
                ["fa", "paperclip"],
                ["fa", "paper-plane"],
                ["fa", "paper-plane-o"],
                ["fa", "pen"],
                ["fa", "pencil"],
                ["fa", "pencil-square-o"],
                ["fa", "phone"],
                ["fa", "picture-o"],
                ["fa", "play-circle"],
                ["fa", "plug"],
                ["fa", "plus"],
                ["fa", "plus-circle"],
                ["fa", "power-off"],
                ["fa", "print"],
                ["fa", "question"],
                ["fa", "question-circle"],
                ["fa", "receipt"],
                ["fa", "recycle"],
                ["fa", "refresh"],
                ["fa", "robot"],
                ["fa", "rss-square"],
                ["fa", "save"],
                ["fa", "search"],
                ["fa", "search-plus"],
                ["fa", "share"],
                ["fa", "share-square"],
                ["fa", "shopping-basket"],
                ["fa", "shopping-cart"],
                ["fa", "signature"],
                ["fa", "sign-in"],
                ["fa", "sign-out"],
                ["fa", "sign-out-alt"],
                ["fa", "sliders"],
                ["fa", "sort-desc"],
                ["fa", "spinner"],
                ["fa", "square-o"],
                ["fa", "stamp"],
                ["fa", "star"],
                ["fa", "sync"],
                ["fa", "table"],
                ["fa", "tachometer"],
                ["fa", "thumbs-up"],
                ["fa", "times"],
                ["fa", "toggle-off"],
                ["fa", "toggle-on"],
                ["fa", "trash"],
                ["fa", "undo"],
                ["fa", "university"],
                ["fa", "upload"],
                ["fa", "user"],
                ["fa", "user-circle"],
                ["fa", "user-edit"],
                ["fa", "user-friends"],
                ["fa", "user-md"],
                ["fa", "user-plus"],
                ["fa", "user-shield"],
                ["fa", "user-tag"],
                ["fa", "users"],
                ["fa", "video"],
                ["fa", "warning"],
                ["fa", "wrench"],

                // FA5+ explicit Solid prefix
                ["fas", "angle-right"],
                ["fas", "arrow-left"],
                ["fas", "arrow-right"],
                ["fas", "ban"],
                ["fas", "box-open"],
                ["fas", "bullhorn"],
                ["fas", "business-time"],
                ["fas", "check"],
                ["fas", "external-link"],
                ["fas", "external-link-alt"],
                ["fas", "globe"],
                ["fas", "key"],
                ["fas", "map-marker-alt"],
                ["fas", "paper-plane"],
                ["fas", "pen"],
                ["fas", "plus"],
                ["fas", "save"],
                ["fas", "shopping-basket"],
                ["fas", "shopping-cart"],
                ["fas", "sign-in-alt"],
                ["fas", "tag"],
                ["fas", "toggle-on"],
                ["fas", "user-lock"],
                ["fas", "user-plus"],

                // FA5+ Regular (the FA6-Free curtailment risk lives here)
                ["far", "calendar-alt"],
                ["far", "clock"],
                ["far", "comments"],
                ["far", "file"],
                ["far", "file-pdf"],
                ["far", "lightbulb"],
                ["far", "question-circle"],

                // Brands
                ["fab", "buffer"],
                ["fab", "facebook"],
            ];
        }
    }

?>
