<?php

    namespace ZubZet\Framework\Core;

    use ZubZet\Framework\Support\StaticCache;

    trait CanManageCache {

        private string $cacheFile = "z_config/z_cache.ini";

        private static string $HEADER = "; This file is auto-generated by the framework to store runtime data. Do not edit this file manually.\n";
        private static string $CACHE_KEY = "CACHE";
        private static string $CACHE_VALUE = "data";

        public function getCache($key = null, $useDefault = true, $default = null) {
            // Check if the cache exists, if not load it
            if(!StaticCache::has(self::$CACHE_KEY, self::$CACHE_VALUE)) {
                $this->loadCache();
            }

            // Get the cache data
            $data = StaticCache::get(self::$CACHE_KEY, self::$CACHE_VALUE);

            // Return all cache data if no key is provided
            if(is_null($key) || empty($key)) return $data;

            // Return specific cache value if it exists
            if(isset($data[$key])) return $data[$key];

            // Return default if enabled
            if($useDefault) return $default;

            throw new \InvalidArgumentException("The cache key '$key' does not exist!");
        }

        public function setCache(string $key, mixed $value): void {
            $this->ensureCacheFile();

            // Load the cache file as individual lines
            $content = file_get_contents($this->cacheFile);
            $lines = $content === "" ? [] : preg_split('/\R/', $content);

            // Surgically update the line for $key, preserving comments and ordering
            $this->modifyCacheLine($lines, $key, $value);

            file_put_contents($this->cacheFile, implode(PHP_EOL, $lines));

            // Mirror the change into StaticCache if it is already loaded
            if(StaticCache::has(self::$CACHE_KEY, self::$CACHE_VALUE)) {
                $data = StaticCache::get(self::$CACHE_KEY, self::$CACHE_VALUE);
                if(!is_array($data)) $data = [];
                $data[$key] = $value;
                StaticCache::set(self::$CACHE_KEY, self::$CACHE_VALUE, $data);
            }
        }

        private function addCacheLine(array &$lines, string $key, mixed $value): void {
            $lines[] = $this->formatCacheLine($key, $value);
        }

        private function modifyCacheLine(array &$lines, string $key, mixed $value): void {
            $lineAt = $this->findCacheLine($lines, $key);

            // If the property doesn't exist, simply create it
            if($lineAt === null) {
                $this->addCacheLine($lines, $key, $value);
                return;
            }

            $formatted = $this->formatCacheLine($key, $value);

            // Skip if the value is already set
            if($lines[$lineAt] === $formatted) return;

            // Otherwise modify the existing value
            $lines[$lineAt] = $formatted;
        }


        private function loadCache() {
            $this->ensureCacheFile();
            $ini_data = file_get_contents($this->cacheFile);

            $config = parse_ini_string($ini_data);
            StaticCache::set(self::$CACHE_KEY, self::$CACHE_VALUE, $config);
        }

        private function ensureCacheFile(): void {
            if(file_exists($this->cacheFile)) return;
            file_put_contents($this->cacheFile, self::$HEADER);
        }

        private function findCacheLine(array $lines, string $key): ?int {
            foreach($lines as $i => $line) {
                $trimmed = trim($line);
                if($trimmed === "") continue;
                if(str_starts_with($trimmed, ';')) continue;
                if(str_starts_with($trimmed, '#')) continue;
                if(!str_contains($line, '=')) continue;

                [$lineKey] = explode('=', $line, 2);
                if(trim($lineKey) === $key) return $i;
            }
            return null;
        }

        private function formatCacheLine(string $key, string $value): string {
            $line = "$key =";
            if($value !== "") $line .= " " . $value;
            return $line;
        }
    }

?>
