<?php

    namespace ZubZet\Framework\Bootstrap;

    /**
     * @internal
     */
    final class AutomatedSettings {

        private static string $HEADER = "; This file is auto-generated by the framework to store runtime data. Do not edit this file manually.";

        private static array $settings = [];

        public static function load(array $settings): void {
            self::$settings = $settings;
        }

        public static function set(string $key, mixed $value): void {
            $key = "automated_$key";

            self::$settings[$key] = $value;

            $configContent = self::$HEADER . PHP_EOL;
            foreach(self::$settings as $settingKey => $settingValue) {
                $configContent .= "$settingKey=$settingValue" . PHP_EOL;
            }

            file_put_contents(config("config_automated_file"), $configContent);
        }
    }

?>
